<?php
$config['site']['invalid_error_msg'] = "Invalid access token";
$config['site']['support_email'] = 'noreply@topstox.com';
$config['site']['admin_email'] = 'admin@topstox.com';
$config['site']['name'] = 'Topstox.com';
$server = "live";
switch($server){
    case "local":
        $config['site']['url'] = 'http://localhost/stox_web/trunk/web_services/1.1/users/setnewpassword/';
        $config['site']['url1'] = 'http://localhost/stox_web/trunk/web_services/1.1/users/createnewpassword/';
        $config['site']['image_path'] = 'http://localhost/stox_web/trunk/web_services/1.1/app/webroot/files/uploads/';
        break;
    case "dev":
        $config['site']['url'] = 'http://tstox.softwaydev.com/1.1/users/setnewpassword/';
        $config['site']['url1'] = 'http://tstox.softwaydev.com/1.1/users/createnewpassword/';
        $config['site']['image_path'] = 'http://tstox.softwaydev.com/1.1/webroot/files/uploads/';
        break;
    case "live":
        $config['site']['url'] = 'http://app.topstox.com/users/setnewpassword/';
        $config['site']['url1'] = 'http://app.topstox.com/users/createnewpassword/';
        $config['site']['image_path'] = 'http://app.topstox.com/app/webroot/files/uploads/';
        break;
    case "staging":
        $config['site']['url'] = 'http://staging.topstox.com/users/setnewpassword/';
        $config['site']['url1'] = 'http://staging.topstox.com/users/createnewpassword/';
        $config['site']['image_path'] = 'http://staging.topstox.com/app/webroot/files/uploads/';
        break;
    case "default":
        $config['site']['url'] = 'http://app.topstox.com/users/setnewpassword/';
        $config['site']['url1'] = 'http://app.topstox.com/users/createnewpassword/';
        $config['site']['image_path'] = 'http://app.topstox.com/app/webroot/files/uploads/';
        break;
}

$config['site']['login_message1'] = 'Logged in Successfully';
$config['site']['login_message2'] = 'Login failed!';
$config['site']['login_message3'] = 'Incorrect Email or Password';
$config['site']['login_message4'] = 'Email could not be logged in.';
$config['site']['login_message5'] = 'Incorrect Email Username or Password';
$config['site']['login_message6'] = 'No param passed';
$config['site']['logout_message1'] = 'Logout Successfully!';
$config['site']['logout_message2'] = 'Logout Failed!';
$config['site']['bio_message1'] = 'Biodata updated Successfully!';
$config['site']['bio_message2'] = 'Failed! Biodata not updated';
$config['site']['editProfile_message1'] = 'Profile has been updated successfully!';
$config['site']['editProfile_message2'] = 'Unable to update profile.';
$config['site']['gameList_message1'] = 'List';
$config['site']['gameList_message2'] = 'Error! Unable to retrieve game list.';
$config['site']['premiumGames_message1'] = 'Game List';
$config['site']['premiumGames_message2'] = 'Failed! Game List could not be shown';
$config['site']['createPortfolio_message1'] = 'Portfolio created successfully!';
$config['site']['createPortfolio_message2'] = 'Error! Creating portfolio!';
$config['site']['createPortfolio_message3'] = 'Error! Max start value exceeded.';
$config['site']['createPortfolio_message4'] = 'Start money can not be zero';
$config['site']['show_portfolio_list_message1'] = 'SUCCESS!';
$config['site']['resetPortfolio_message1'] = 'Portfolio has been reset successfully!';
$config['site']['resetPortfolio_message2'] = 'Error! Resetting portfolio!';
$config['site']['addWatchlist_message1'] = 'Item added to Watchlist!';
$config['site']['addWatchlist_message2'] = 'Error! Unable to update Watchlist.';
$config['site']['addWatchlist_message3'] = 'Error! You are already watching this item';
$config['site']['addWatchlist_message4'] = 'Portfolio does not exist for the user';
$config['site']['showWatchlist_message1'] = 'Success!';
$config['site']['showWatchlist_message2'] = 'Watchlist is empty!';
$config['site']['register_message1'] = 'Registration failed!';
$config['site']['register_message2'] = 'This username is already in use.';
$config['site']['register_message3'] = 'This email address is already in use.';
$config['site']['forgotPassword_message1'] = 'An email has been sent to your registered email ID.';
$config['site']['forgotPassword_message2'] = 'Oops! Something went wrong. Please try again later';
$config['site']['forgotPassword_message3'] = 'The email or username does not exist in our system';
$config['site']['showBankData_message1'] = 'Success!';
$config['site']['showBankData_message2'] = 'Error! Cannot display data.';
$config['site']['showBankData_message3'] = 'Game List';
$config['site']['showBankData_message4'] = 'Failed! Game List could not be shown';
$config['site']['changePassword_message1'] = 'Password change successful!';
$config['site']['changePassword_message2'] = 'Password change failed!';
$config['site']['changePassword_message3'] = 'Password mismatch!';
$config['site']['changePassword_message4'] = 'Invalid Password!';
$config['site']['get_share_data_message1'] = 'Share Data';
$config['site']['get_share_data_message2'] = 'The stock could not be found';
$config['site']['get_share_data_message3'] = 'Page number should not be 0 or less';
$config['site']['upload_image_message1'] = 'Image has been updated successfully!';
$config['site']['upload_image_message2'] = 'Failed! Image has not been updated';
$config['site']['buy_cash_trade_message1'] = 'Data has been saved successfully';
$config['site']['buy_cash_trade_message2'] = 'Data has not been saved';
$config['site']['social_login_message1'] = 'Error! FB Registration failed!';
$config['site']['social_login_message2'] = 'Failed! Something Went wrong.Please try again later.';
$config['site']['buy_stocks_message1'] = 'User does not have enough Trade/Cash to make this transaction';
$config['site']['buy_stocks_message2'] = 'Stock has been bought successfully';
$config['site']['buy_stocks_message3'] = 'Portfolio data is not correct';
$config['site']['buy_stocks_message4'] = 'Markets are closed now!';
$config['site']['sell_stocks_message1'] = 'User does not have enough Trade';
$config['site']['sell_stocks_message2'] = 'Stock has been sold successfully';
$config['site']['sell_stocks_message3'] = 'Please send the correct quantity';
$config['site']['sell_stocks_message4'] = 'No shares available for sale';
$config['site']['sell_stocks_message5'] = 'Markets are closed now!';
$config['site']['user_stocks_message1'] = 'Successfully fetched';
$config['site']['user_stocks_message2'] = 'No Share Available';
$config['site']['user_stocks_message3'] = 'Error! something went wrong!';
$config['site']['user_stocks_message5'] = 'No param passed';
$config['site']['stock_history_message1'] = 'Success';
$config['site']['stock_history_message2'] = 'No data';
$config['site']['stock_history_message3'] = 'Error';
$config['site']['stock_history_message5'] = 'No param passed';
$config['site']['pending_stocks_message1'] = 'Success';
$config['site']['pending_stocks_message2'] = 'No data';
$config['site']['pending_stocks_message3'] = 'Error! Oops something went wrong!';
$config['site']['pending_stocks_message5'] = 'No param passed';
$config['site']['faq_data_message1'] = 'Success!';
$config['site']['faq_data_message2'] = 'Error! FAQ data';
$config['site']['feedback_data_message1'] = 'Success! : Your query has been submitted.';
$config['site']['feedback_data_message2'] = 'Error! Feedback data';
$config['site']['contactus_data_message1'] = 'Success!Contact us data';
$config['site']['contactus_data_message2'] = 'Error! Contact us data';
$config['site']['remove_from_watchlist_message1'] = 'Item has been removed from the watchlist successfully';
$config['site']['remove_from_watchlist_message2'] = 'Error! Watchlist couldnt not be shown';
$config['site']['portfolio_detail_message1'] = 'Success! Portfolio Details';
$config['site']['set_active_portfolio_message1'] = 'Current Portfolio Set';
$config['site']['set_active_portfolio_message2'] = 'No data';
$config['site']['share_detail_message1'] = 'Suceess! share data';
$config['site']['share_detail_message2'] = 'Error! No Data';
$config['site']['notification_list_message1'] = 'Success! Notification List';
$config['site']['notification_list_message2'] = 'Error! No Data';
$config['site']['polling_count_message1'] = 'Success! Polling notification;';
$config['site']['send_ios_notification_message'] = 'APPLE PUSH NOTIFICATION SEND FROM API COMPONENT INSIDE';
$config['site']['notification_profit_message'] = 'You have made $ at the end of the day today';
$config['site']['notication_loss_message'] = 'You Lost $ at the end of the day today';
$config['site']['notification_equal_message'] = 'You didn\'t lose or gain anything at the end of the day today';
$config['site']['daytrade_notification_title'] = "TopSTOX - Day-Trade end of the day report";
$config['site']['splash_screen_message1'] = 'Success';
$config['site']['sync_message1'] = 'Upgraded Successfully';
